name: generate-png-from-mermaid
on:
  push:
    branches-ignore: [main]
    paths:
      - 'images/*.mermaid'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.CREATE_PR_TOKEN }}
      - name: Get source changes
        id: source_changes
        run: |
          echo "::set-output name=files::$(git diff --no-commit-id --name-only HEAD^ HEAD | grep -e '.*\.mermaid$' | xargs)"
      - name: Show source changes
        run: |
          echo ${{ steps.source_changes.outputs.files }}
      - name: Compile mermaid
        if: steps.source_changes.outputs.files != ''
        uses: neenjaw/compile-mermaid-markdown-action@0.2.4
        with:
          files: ${{ steps.source_changes.outputs.files }}
          output: 'images'
      - name: Get result changes
        id: result_changes
        run: |
          echo "::set-output name=files::$(git status -s)"
      - name: Show result changes
        if: steps.source_changes.outputs.files != ''
        run: |
          echo ${{ steps.result_changes.outputs.files }}
      - name: Rename result files
        if: steps.source_changes.outputs.files != ''
        run: |
            for i in images/*-mermaid.png; do mv "$i" "${i%-mermaid.png}.png"; done
      - name: Add files
        if: steps.result_changes.outputs.files != ''
        run: |
          git add images/*
      - name: Commit and push changes
        if: steps.result_changes.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: generate images'
          file_pattern: 'images/*'
